//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> grossSalary { get; set; }
        public Nullable<int> designation { get; set; }
        public string empImage { get; set; }
        public virtual tblDesignation tblDesignation { get; set; }
    }
}
